// <auto-generated />
namespace HospitalApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class added_doctor_to_prescription : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_doctor_to_prescription));
        
        string IMigrationMetadata.Id
        {
            get { return "202106051554113_added_doctor_to_prescription"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
