// <auto-generated />
namespace HospitalApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
<<<<<<< HEAD:Project code/HospitalApp/HospitalApp/Migrations/202106051554113_added_doctor_to_prescription.Designer.cs
    public sealed partial class added_doctor_to_prescription : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_doctor_to_prescription));
        
        string IMigrationMetadata.Id
        {
            get { return "202106051554113_added_doctor_to_prescription"; }
=======
    public sealed partial class mig2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig2));
        
        string IMigrationMetadata.Id
        {
            get { return "202106021613107_mig2"; }
>>>>>>> 1f4f13466c4917fffabd4cf21804f3c48254d116:Project code/HospitalApp/HospitalApp/Migrations/202106021613107_mig2.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
