// <auto-generated />
namespace HospitalApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class hospitalDBv1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hospitalDBv1));
        
        string IMigrationMetadata.Id
        {
            get { return "202103301101222_hospitalDB-v1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
